<?php
  $menu_icons = array('Users'=> 'mdi mdi-account-box',
                     'Rojmel'=> 'mdi mdi-bullseye',
                     'Masters' => 'fa fa-black-tie',
                     'Transaction' => 'fa fa-exchange',
                     'MIS Report' => 'fa fa-file-text',
                     'Stock Report' => 'fa fa-line-chart',
                     'Order Report' => 'fa fa-line-chart',
                     'Interest'     => 'fa fa-percent',
                     'Other'        => 'fa fa-question-circle');

  $main_menu =  array('Users'  => array('users/users'=>'Users',
                                      'users/user_roles'=>'User roles'),
                     // 'Rojmel'  => array('rojmel/rojmel'=>'Rojmel'),
                     'Masters' => array('masters/accounts'=>'Accounts',
                                        'masters/groups' =>'Group',
                                        'masters/purity'=>'Purity',
                                        'masters/company'=>'Company',
                                        'masters/payment_terms'=>'Payment Terms',
                                        'masters/opening_balance'=>'Opening Balance',
                                        'masters/department'=>'Department',
                                        'masters/customer_category'=>'Customer Category',
                                        'masters/department_category'=>'Department Category',
                                        'masters/periods'=>'Financial Year'),
                    'Transactions' => array(
                                            // 'transactions/cash_issue_vouchers' => 'Cash Issue Voucher',
                                            // 'transactions/cash_receipt_vouchers' => 'Cash Receipt Voucher',
                                            // 'transactions/bank_issue_voucher'=> 'Bank Issue Voucher',
                                            // 'transactions/bank_receipt_voucher' => 'Bank Receipt Voucher',
                                            'transactions/metal_issue_vouchers' => 'Metal Issue Voucher',
                                            'transactions/metal_receipt_vouchers' => 'Metal Receipt Voucher',
                                            // 'transactions/sales_voucher' => 'Sales Voucher',
                                            // 'transactions/purchase_voucher' => 'Purchase Voucher',
                                            // 'transactions/journal_voucher' => 'Journal Voucher',
                                            // 'transactions/contra_voucher' => 'Contra Voucher',
                                            // 'transactions/rate_cut_purchase_price_issue_voucher' => 'Rate Cut Purchase Price Issue Voucher',
                                            // 'transactions/rate_cut_purchase_weight_issue_voucher' => 'Rate Cut Purchase Weight Issue Voucher',
                                            // 'transactions/rate_cut_purchase_price_receipt_voucher' => 'Rate Cut Purchase Price Receipt Voucher',
                                            // 'transactions/rate_cut_purchase_weight_receipt_voucher' => 'Rate Cut Purchase Weight Receipt Voucher',
                                            // 'transactions/rate_cut_booking_price_issue_voucher' => 'Rate Cut Booking Price Issue Voucher',
                                            // 'transactions/rate_cut_booking_weight_issue_voucher' => 'Rate Cut Booking Weight Issue Voucher',
                                            // 'transactions/rate_cut_booking_price_receipt_voucher' => 'Rate Cut Booking Price Receipt Voucher',
                                            // 'transactions/rate_cut_booking_weight_receipt_voucher' => 'Rate Cut Booking Weight Receipt Voucher',
                                            // 'transactions/dispatch_voucher' => 'Dispatch Voucher',
                                            // 'transactions/repair_voucher' => 'Repair Voucher',
                                            // 'transactions/approval_voucher' => 'Approval Voucher',
                                            // 'transactions/expense_voucher' => 'Expense Voucher',
                                            // 'transactions/transfer_voucher' => 'Transfer Voucher',
                                            // 'transactions/repair_voucher_out' => 'Repair Voucher Out',
                                            // 'transactions/approval_in_voucher' => 'Approval in Voucher',
                                            // 'transactions/opening_stock_voucher' => 'Opening Stock Voucher',
                                            // 'transactions/sales_return_voucher' => 'Sales Return Voucher',
                                            // 'transactions/antique_sales_voucher' => 'Antique Sales Voucher',
                                            // 'transactions/mangalsutra_sales_voucher' => 'Mangalsutra Sales Voucher',
                                            // 'transactions/platinum_sales_voucher' => 'Platinum Sales Voucher',
                                            // 'transactions/machine_bangles_sales_voucher' => 'Machine Bangles Sales Voucher',
                                            // 'transactions/antique_sales_return_voucher' => 'Antique Sales Return Voucher',
                                            // 'transactions/mangalsutra_sales_return_voucher' => 'Mangalsutra Sales Return Voucher'
                                          ),
                    // 'Reports'   => array('reports/mis_reports'=>'MIS Reports',
                    //                     'reports/stock_report' =>'Stock Report',
                    //                     'reports/order_report'=>'Order Report'),
                    'Reports'   => array('reports/account_ledger_reports' => 'Account Ledger',
                                        'reports/client_account_ledger_reports' => 'Client Account Ledger',
                                        'reports/vadotar_reports' => 'Vadotar Report',
                                        'reports/rojmel_reports' => 'Rojmel Report'),
                    // 'Interests' => array('interests/interest_issue_voucher'=>'Interest Issue Voucher'),
                    // 'Others'    => array('others/account_wise_details'=>'Account Wise Details',
                    //                     'others/category'=>'Category',
                    //                     'others/item'=>'Item',
                    //                     'others/city'=>'City',
                    //                     'others/state'=>'State',
                    //                     'others/salesman'=>'Sales Man',
                    //                     'others/narration'=>'Narration',
                    //                     'others/book'=>'Book',
                    //                     'others/sms'=>'SMS'),

                ); 
  $this->load->view('navigation/application/sidebar', 
                  array('main_menu' => $main_menu, 'menu_icons' => $menu_icons)); 
?>



